namespace FamilyTree.AcceptanceTests.Support;

/// <summary>Per-scenario scratch state shared between step classes via Reqnroll context injection.
/// Mainly a name-to-id map, since person ids are generated by the app rather than chosen by the test.</summary>
public sealed class ScenarioState
{
    private readonly Dictionary<string, string> _idsByName = new(StringComparer.OrdinalIgnoreCase);

    public string? LastRedirectLocation { get; set; }

    public void RememberId(string name, string id) => _idsByName[name] = id;

    public string IdFor(string name) => _idsByName.TryGetValue(name, out var id)
        ? id
        : throw new InvalidOperationException($"No person named '{name}' has been created yet in this scenario.");
}
